// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQn6UHYvtWzS_aU-4wSpHTJiw7rou-vs',
    appId: '1:209972072168:web:3cde2e0b7d9f3ae5a0c35d',
    messagingSenderId: '209972072168',
    projectId: 'drug-pedia',
    authDomain: 'drug-pedia.firebaseapp.com',
    storageBucket: 'drug-pedia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OqNlKJLxbKHAMBeittEctFrWGQ59RNc',
    appId: '1:209972072168:android:beb14c0eba668b72a0c35d',
    messagingSenderId: '209972072168',
    projectId: 'drug-pedia',
    storageBucket: 'drug-pedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtVijjwxn8Rwckp82EX88LqNIq_99Xrs',
    appId: '1:209972072168:ios:7d9e89e2b33b80d2a0c35d',
    messagingSenderId: '209972072168',
    projectId: 'drug-pedia',
    storageBucket: 'drug-pedia.appspot.com',
    androidClientId: '209972072168-bcba508bn7dkl9op02b7s7s1meaaucmo.apps.googleusercontent.com',
    iosClientId: '209972072168-7fbtpjutvjr7p83diqv6dc3a8mh1glh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.drugpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHtVijjwxn8Rwckp82EX88LqNIq_99Xrs',
    appId: '1:209972072168:ios:7909eb2b36573d6ca0c35d',
    messagingSenderId: '209972072168',
    projectId: 'drug-pedia',
    storageBucket: 'drug-pedia.appspot.com',
    androidClientId: '209972072168-bcba508bn7dkl9op02b7s7s1meaaucmo.apps.googleusercontent.com',
    iosClientId: '209972072168-5037qtsu8s56v7tuicphgn9anbgi345t.apps.googleusercontent.com',
    iosBundleId: 'com.example.drugpedia.RunnerTests',
  );
}
